### ISSUE TITLE
Is Autopatch still maintained?

### ISSUE THREAD

**Issue by mikehardy** [tacitknowledge/autopatch#48]
Hey @danvalencia  and @scottfromsf - is anyone working on this that you know of? I may have a use for it, and I've got maven namespace at net.mikehardy - looks like this is dead here but if a different project I'm working on is okay with using this, I could fork, move it to net.mikehardy and move it forward. I don't want to step on anyone's toes though, and maybe I'm missing some better solution that exists in Java land now?

**Comment by witherspore** [comment]
It’s pretty dead, but tacit owns the copyright.  

There’s better java dB migration tools available, especially when considering environment needs for seeding stuff like QA data.  Also, the handle the various ddm and ddl rollback techniques more easily.

Auto patch does still lead for data sharding, and I’d probably use it there.  Of course you are also very familiar with the code.

I’d reach out to Prithpal Roda about putting it on github and doing a fork.  Proda at Tk.

Matthew Short
415 272-6648
Witherspore@gmail.com

**Comment by witherspore** [comment]
Adding others

Matthew Short
415 272-6648
Witherspore@gmail.com

**Comment by witherspore** [comment]
Liquibase and flyway are where to start for mainstream stuff.

Matthew Short
415 272-6648
Witherspore@gmail.com

**Comment by mikehardy** [comment]
Hey thanks a bunch Matt - I don't need another project to maintain if I can avoid it so I'll look at the two you mentioned, since sharding isn't part of my projects needs

**Comment by witherspore** [comment]
Do check which ones are supported by environment management tools like terraform.  Will save a lot of work.

Matthew Short
415 272-6648
Witherspore@gmail.com

**Comment by danvalencia** [comment]
Hey guys! ✌️

We’re been using Flyway, with zero issues. It has support for SQL and Java patches.

Hope you’re both doing well.

Cheers,
-Daniel

**Comment by mikehardy** [comment]
Hey guys - I want to close this out. Thanks a bunch for the pointers.

I see the license is Apache 2, so to my original issue, this is forkable by anyone and as it seems pretty dead, if anyone wants to do this it shouldn't step on toes. "Someone" should update it similar to some of the other tacitknowledge github repos to mention it's basically deprecated and that flyway or liquibase are better choices these days.

Then digging into those, it looks like flyway is the most flexible as liquibase appears to be very very SQL focused and has a single changelist file, while flyway does the classpath migration loading that autopatch here does, and can load .sql or Java objects to apply, allowing for easy coordination of the various persisted bits applications seem to build up outside of databases, along with the database schema.

Also, seems if terraform is your thing you can hook flyway on database instantiation like so https://github.com/hashicorp/terraform/issues/10740#issuecomment-267224310

Again, I really appreciate the pointers in this. Funny to read the copyright headers in here dating back to 2004 (2004!!?!) so I'm clearly back to novice level in the space and it was helpful to quickly get pointers to the state of the art from a couple of trusted friends. Cheers
